using ADORM.Domain.Contexts;
using ADORM.Domain.Roles.Template;
using System;
using System.IO;

namespace ADORM.Domain.Objects.Template
{
    public abstract class BaseTemplate : ITemplate
    {
        public static string Profile => $"/* Generated by ADORM on {DateTime.Now:yyyy-MM-dd HH:mm:ss} */";

        public virtual TemplateContext Context { get; set; }

        public abstract string NameSpace { get; }

        public virtual string FolderPath => string.IsNullOrWhiteSpace(NameSpace) ? Context.OutputFolder : Path.Combine(Context.OutputFolder, NameSpace);

        public abstract string FileName { get; }

        public virtual string FilePath => Path.Combine(FolderPath, FileName);

        public abstract string FileContent { get; }

        public virtual void Generate()
        {
            Logger.Info($"{NameSpace} > {FileName} is generating...");
            File.WriteAllText(FilePath, FileContent);
        }
    }
}
